### ISSUE TITLE
Calculating Catalan Numbers Efficiently

### ISSUE THREAD

**Issue by yashagarwal1999** [rishabhgarg25699/Competitive-Programming#103]
Catalan numbers are often asked in competitive codin competitiions. Can I Work on this issue?

**Comment by yashagarwal1999** [comment]
Solved this issue in #102

**Comment by yashagarwal1999** [comment]
Can I work on this?

**Comment by rishabhgarg25699** [comment]
@yashagarwal1999 One issue at one time
