### ISSUE TITLE
Computing Euler Totient Function in sqrt(N)

### ISSUE THREAD

**Issue by yashagarwal1999** [rishabhgarg25699/Competitive-Programming#104]
Euler Totient function is a function that gives the number of coprime integers from 1 to N. This algorithm will compute the number of coprime integers for any given N in sqrt(N) time.  I would like to work on this.

**Comment by yashagarwal1999** [comment]
Solved in #102

**Comment by yashagarwal1999** [comment]
Can I work on this?

**Comment by rishabhgarg25699** [comment]
@yashagarwal1999 One issue at one time.
