### ISSUE TITLE
Dijkstra's algorithm in C++

### ISSUE THREAD

**Issue by hrishibhattu** [rishabhgarg25699/Competitive-Programming#120]
I would like to implement it.

**Comment by rishabhgarg25699** [comment]
@hrishibhattu Assigned

**Comment by ankur54** [comment]
hey is this issue been worked on? Can I work on it?

**Comment by hrishibhattu** [comment]
Alright, I'm unable to give it enough time due to exams, you can work on it.

**Comment by ashishugi** [comment]
can i work on this issue ?

**Comment by hrishibhattu** [comment]
I'm going to close this issue now as I'm unable to work on it. Please open a new issue for this.
