### ISSUE TITLE
Various searching algorithms

### ISSUE THREAD

**Issue by RashakDude** [rishabhgarg25699/Competitive-Programming#146]
The various searching algorithms - 
* Linear Search
* Binary Search
* Jump Search
* Interpolation Search
* Exponential Search

**Comment by RashakDude** [comment]
I would like to add these various searching algorithms,

**Comment by rishabhgarg25699** [comment]
@RashakDude Make a folder and add all these

**Comment by RashakDude** [comment]
@rishabhgarg25699 I have already added the files in the folder ' Searching Algo '. Please check and merge :)

**Comment by RashakDude** [comment]
Added various search algorithms in Python as PR #150
