### ISSUE TITLE
Stable Marriage Problem

### ISSUE THREAD

**Issue by Satvinder31415** [rishabhgarg25699/Competitive-Programming#206]
Solve the stable marriage problem. CodeChef Problem Code: STABLEMP

**Comment by rishabhgarg25699** [comment]
@Satvinder31415 No codechef problem. Only algo

**Comment by Satvinder31415** [comment]
@rishabhgarg25699  It is a well known problem if I am not mistaken and is present in one of the books you mentioned as well as on the geeksforgeeks website
