### ISSUE TITLE
Introducing problems in backtracking

### ISSUE THREAD

**Issue by RashakDude** [rishabhgarg25699/Competitive-Programming#213]
I wanna add the problems from Geeks for Geeks in a folder on backtracking - 
* The Knight's Tour problem
* Rat in a maze
* N Queen problem
* Subset Sum
* m Coloring problem
* Hamiltonian Cycle

**Comment by rishabhgarg25699** [comment]
@RashakDude Not from GFG. You had to write algo on your own.

**Comment by BhallalDev22** [comment]
I've submitted the pull request for this issue i.e 'Introducing problems in backtracking' and this issue is close now. Thank you

**Comment by BhallalDev22** [comment]
Sir I've submitted the pull request for issue #213 please close it.
