### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by rishabhgarg25699** [rishabhgarg25699/Competitive-Programming#282]
Given two sequences, find the length of longest subsequence present in both of them. A subsequence is a sequence that appears in the same relative order, but not necessarily contiguous. For example, “abc”, “abg”, “bdf”, “aeg”, ‘”acefg”, .. etc are subsequences of “abcdefg”.

**Comment by krish7777** [comment]
@rishabhgarg25699 I would like to work on this issue.

**Comment by ashishrrs** [comment]
Plizz assign this to me

**Comment by ishi0301** [comment]
please assign me this

**Comment by onbit-uchenik** [comment]
Please assign to me.:)

**Comment by rishabhgarg25699** [comment]
@onbitSyn You have assigned
