### ISSUE TITLE
Longest Palindromic Substring 

### ISSUE THREAD

**Issue by rishabhgarg25699** [rishabhgarg25699/Competitive-Programming#283]
Given a string, find the longest substring which is palindrome.
For example,

Input: Given string :"forgeeksskeegfor", 
Output: "geeksskeeg"

Input: Given string :"Geeks", 
Output: "ee"

**Comment by Vrindagupta6828** [comment]
@rishabhgarg25699  please assign this to me.

**Comment by rishabhgarg25699** [comment]
@Vrindagupta6828 This is not for you. If you want, please open the issue, I will assign you the issue

**Comment by onbit-uchenik** [comment]
@rishabhgarg25699 Please allow me to solve this issue.

**Comment by rishabhgarg25699** [comment]
@onbitSyn Assigned
