### ISSUE TITLE
Subset Sum Problem

### ISSUE THREAD

**Issue by rishabhgarg25699** [rishabhgarg25699/Competitive-Programming#284]
Given a non-empty array containing only positive integers, find if the array can be partitioned into two subsets such that the sum of elements in both subsets is equal.

Input: [1, 5, 11, 5]

Output: true

Explanation: The array can be partitioned as [1, 5, 5] and [11].

**Comment by Aastha26-lab** [comment]
Hey @rishabhgarg25699 , Can I  work on this issue . Please ?

**Comment by rishabhgarg25699** [comment]
@Aastha26-lab This is not for you. If you want, open the issue and I will assign you.

**Comment by Aastha2602** [comment]
I got that

**Comment by onbit-uchenik** [comment]
Please allow me to solve this issue. :)

**Comment by rishabhgarg25699** [comment]
@onbitSyn Assigned
