### ISSUE TITLE
Word Break Problem

### ISSUE THREAD

**Issue by rishabhgarg25699** [rishabhgarg25699/Competitive-Programming#285]
Given an input string and a dictionary of words, find out if the input string can be segmented into a space-separated sequence of dictionary words. See following examples for more details.
This is a famous Google interview question, also being asked by many other companies now a days.

Consider the following dictionary 
{ i, like, sam, sung, samsung, mobile, ice, 
  cream, icecream, man, go, mango}

Input:  ilike
Output: Yes 
The string can be segmented as "i like".

Input:  ilikesamsung
Output: Yes
The string can be segmented as "i like samsung" 
or "i like sam sung".

**Comment by Ajit-53** [comment]
plz assign me ..i will solve this issue.

**Comment by ashishrrs** [comment]
I would like to work on this

**Comment by onbit-uchenik** [comment]
Please allow me to solve this issue.

**Comment by rishabhgarg25699** [comment]
@onbitSyn Assigned
