### ISSUE TITLE
Linked List Implementation In Python

### ISSUE THREAD

**Issue by rishabhgarg25699** [rishabhgarg25699/Competitive-Programming#307]
Write a program which implements Linked list in python and please implement different function of Linked List.

**Comment by abhinavarora14799** [comment]
Okay Sounds Good, working on it right now.

**Comment by abhinavarora14799** [comment]
Ready to merge the implementation, the styling component has been implemented too, make license, make pretty, and make test-all tests passed. Ready to merge.

**Comment by rishabhgarg25699** [comment]
@abhinavarora14799  Give me Pull Request

**Comment by abhinavarora14799** [comment]
Pull request sent @rishabhgarg25699.
