### ISSUE TITLE
regarding java

### ISSUE THREAD

**Issue by Knlsharma** [rishabhgarg25699/Competitive-Programming#47]
There is less code support for java in this repo. Can I add it in java?

Such as Binary Search, Insertion sort, Trees and Graphs, etc.

**Comment by rishabhgarg25699** [comment]
@Knlsharma Please give the Specific name for the issue, which algorithm you want to implement.

**Comment by Knlsharma** [comment]
> @Knlsharma Please give the Specific name for the issue, which algorithm you want to implement.

**Dfs and Ternary search tree. Is this assigned or not?**
