### ISSUE TITLE
Implement Binary Search Tree

### ISSUE THREAD

**Issue by 4shutosh** [rishabhgarg25699/Competitive-Programming#49]
I would like to work on this.

**Comment by ayush-krishna** [comment]
I would like to take up this issue

**Comment by 4shutosh** [comment]
Hey @ayush-krishna  it's an issue created by me so I would like to work on this. Would you please work on some other issue or create your own one?

**Comment by rishabhgarg25699** [comment]
@4shutosh Assigned.
