### ISSUE TITLE
Implement Linked List Operations

### ISSUE THREAD

**Issue by meganindya** [rishabhgarg25699/Competitive-Programming#53]
* Loop Detection in a Singly Linked List
* Intersection Detection of two Singly Linked Lists

**Comment by yashica-patodia** [comment]
Can i address this issue?

**Comment by meganindya** [comment]
@yashica-patodia Do you want to use C++?

**Comment by yashica-patodia** [comment]
yes

**Comment by rishabhgarg25699** [comment]
@meganindya Assigned
